import type {
  DesktopDashboardRowType,
  MobileDashboardRowType,
  TabletDashboardRowType,
} from '@utils/types/Dashboard';

export const homePageDesktopDashboardRows: DesktopDashboardRowType[] = [
  {
    row: 1,
    col: 4,
    items: [
      {
        row: 1,
        col: 1,
        rowSpan: 1,
        colSpan: 4,
        elementId: 0,
      },
    ],
  },
  {
    row: 2,
    col: 4,
    items: [
      {
        row: 1,
        col: 1,
        rowSpan: 1,
        colSpan: 1,
        elementId: 1,
      },
      {
        row: 2,
        col: 1,
        rowSpan: 1,
        colSpan: 1,
        elementId: 2,
      },
      {
        row: 1,
        col: 2,
        rowSpan: 1,
        colSpan: 1,
        elementId: 3,
      },
      {
        row: 2,
        col: 2,
        rowSpan: 1,
        colSpan: 1,
        elementId: 4,
      },
      {
        row: 1,
        col: 3,
        rowSpan: 2,
        colSpan: 1,
        elementId: 5,
      },
      {
        row: 1,
        col: 4,
        rowSpan: 1,
        colSpan: 1,
        elementId: 6,
      },
      {
        row: 2,
        col: 4,
        rowSpan: 1,
        colSpan: 1,
        elementId: 7,
      },
    ],
  },
  {
    row: 2,
    col: 3,
    items: [
      {
        row: 1,
        col: 1,
        rowSpan: 2,
        colSpan: 1,
        elementId: 8,
      },
      {
        row: 1,
        col: 2,
        rowSpan: 2,
        colSpan: 1,
        elementId: 9,
      },
      {
        row: 1,
        col: 3,
        rowSpan: 2,
        colSpan: 1,
        elementId: 10,
      },
    ],
  },
  {
    row: 2,
    col: 3,
    items: [
      {
        row: 1,
        col: 1,
        rowSpan: 2,
        colSpan: 1,
        elementId: 11,
      },
      {
        row: 1,
        col: 2,
        rowSpan: 2,
        colSpan: 1,
        elementId: 12,
      },
      {
        row: 1,
        col: 3,
        rowSpan: 2,
        colSpan: 1,
        elementId: 13,
      },
    ],
  },
  {
    row: 2,
    col: 3,
    items: [
      {
        row: 1,
        col: 1,
        rowSpan: 2,
        colSpan: 1,
        elementId: 14,
      },
      {
        row: 1,
        col: 2,
        rowSpan: 2,
        colSpan: 1,
        elementId: 15,
      },
      {
        row: 1,
        col: 3,
        rowSpan: 2,
        colSpan: 1,
        elementId: 16,
      },
    ],
  },
  {
    row: 2,
    col: 3,
    items: [
      {
        row: 1,
        col: 1,
        rowSpan: 2,
        colSpan: 2,
        elementId: 17,
      },
      {
        row: 1,
        col: 3,
        rowSpan: 2,
        colSpan: 1,
        elementId: 18,
      },
    ],
  },
  {
    row: 2,
    col: 3,
    items: [
      {
        row: 1,
        col: 1,
        rowSpan: 2,
        colSpan: 1,
        elementId: 19,
      },
    ],
  },
];

export const homePageTabletDashboardRows: TabletDashboardRowType[] = [
  {
    row: 1,
    col: 3,
    items: [
      {
        row: 1,
        col: 1,
        rowSpan: 1,
        colSpan: 3,
        elementId: 0,
      },
    ],
  },
  {
    row: 2,
    col: 2,
    items: [
      {
        row: 1,
        col: 1,
        rowSpan: 1,
        colSpan: 1,
        elementId: 1,
      },
      {
        row: 2,
        col: 1,
        rowSpan: 1,
        colSpan: 1,
        elementId: 2,
      },
      {
        row: 1,
        col: 2,
        rowSpan: 1,
        colSpan: 1,
        elementId: 3,
      },
      {
        row: 2,
        col: 2,
        rowSpan: 1,
        colSpan: 1,
        elementId: 4,
      },
    ],
  },
  {
    row: 2,
    col: 2,
    items: [
      {
        row: 1,
        col: 1,
        rowSpan: 2,
        colSpan: 1,
        elementId: 5,
      },
      {
        row: 1,
        col: 2,
        rowSpan: 1,
        colSpan: 1,
        elementId: 6,
      },
      {
        row: 2,
        col: 2,
        rowSpan: 1,
        colSpan: 1,
        elementId: 7,
      },
    ],
  },
  {
    row: 2,
    col: 2,
    items: [
      {
        row: 1,
        col: 1,
        rowSpan: 2,
        colSpan: 1,
        elementId: 8,
      },
      {
        row: 1,
        col: 2,
        rowSpan: 2,
        colSpan: 1,
        elementId: 9,
      },
    ],
  },
  {
    row: 2,
    col: 2,
    items: [
      {
        row: 1,
        col: 1,
        rowSpan: 2,
        colSpan: 1,
        elementId: 10,
      },
      {
        row: 1,
        col: 2,
        rowSpan: 2,
        colSpan: 1,
        elementId: 11,
      },
    ],
  },
  {
    row: 2,
    col: 2,
    items: [
      {
        row: 1,
        col: 1,
        rowSpan: 2,
        colSpan: 1,
        elementId: 12,
      },
      {
        row: 1,
        col: 2,
        rowSpan: 2,
        colSpan: 1,
        elementId: 13,
      },
    ],
  },
  {
    row: 2,
    col: 2,
    items: [
      {
        row: 1,
        col: 1,
        rowSpan: 2,
        colSpan: 1,
        elementId: 14,
      },
      {
        row: 1,
        col: 2,
        rowSpan: 2,
        colSpan: 1,
        elementId: 15,
      },
    ],
  },
  {
    row: 2,
    col: 2,
    items: [
      {
        row: 1,
        col: 1,
        rowSpan: 2,
        colSpan: 2,
        elementId: 17,
      },
    ],
  },
  {
    row: 2,
    col: 2,
    items: [
      {
        row: 1,
        col: 1,
        rowSpan: 2,
        colSpan: 1,
        elementId: 16,
      },
      {
        row: 1,
        col: 2,
        rowSpan: 2,
        colSpan: 1,
        elementId: 18,
      },
    ],
  },
  {
    row: 2,
    col: 2,
    items: [
      {
        row: 1,
        col: 1,
        rowSpan: 2,
        colSpan: 1,
        elementId: 19,
      },
    ],
  },
];

export const homePageMobileDashboardRows: MobileDashboardRowType[] = [
  {
    row: 33,
    col: 1,
    items: [
      {
        row: 1,
        col: 1,
        rowSpan: 1,
        colSpan: 1,
        elementId: 0,
      },
      {
        row: 2,
        col: 1,
        rowSpan: 1,
        colSpan: 1,
        elementId: 1,
      },
      {
        row: 3,
        col: 1,
        rowSpan: 1,
        colSpan: 1,
        elementId: 2,
      },
      {
        row: 4,
        col: 1,
        rowSpan: 1,
        colSpan: 1,
        elementId: 3,
      },
      {
        row: 5,
        col: 1,
        rowSpan: 1,
        colSpan: 1,
        elementId: 4,
      },
      {
        row: 6,
        col: 1,
        rowSpan: 2,
        colSpan: 1,
        elementId: 5,
      },
      {
        row: 8,
        col: 1,
        rowSpan: 1,
        colSpan: 1,
        elementId: 6,
      },
      {
        row: 9,
        col: 1,
        rowSpan: 1,
        colSpan: 1,
        elementId: 7,
      },
      {
        row: 10,
        col: 1,
        rowSpan: 2,
        colSpan: 1,
        elementId: 8,
      },
      {
        row: 12,
        col: 1,
        rowSpan: 2,
        colSpan: 1,
        elementId: 9,
      },
      {
        row: 14,
        col: 1,
        rowSpan: 2,
        colSpan: 1,
        elementId: 10,
      },
      {
        row: 16,
        col: 1,
        rowSpan: 2,
        colSpan: 1,
        elementId: 11,
      },
      {
        row: 18,
        col: 1,
        rowSpan: 2,
        colSpan: 1,
        elementId: 12,
      },
      {
        row: 20,
        col: 1,
        rowSpan: 2,
        colSpan: 1,
        elementId: 13,
      },
      {
        row: 22,
        col: 1,
        rowSpan: 2,
        colSpan: 1,
        elementId: 14,
      },
      {
        row: 24,
        col: 1,
        rowSpan: 2,
        colSpan: 1,
        elementId: 15,
      },
      {
        row: 26,
        col: 1,
        rowSpan: 2,
        colSpan: 1,
        elementId: 16,
      },
      {
        row: 28,
        col: 1,
        rowSpan: 2,
        colSpan: 1,
        elementId: 17,
      },
      {
        row: 30,
        col: 1,
        rowSpan: 2,
        colSpan: 1,
        elementId: 18,
      },
      {
        row: 32,
        col: 1,
        rowSpan: 2,
        colSpan: 1,
        elementId: 19,
      },
    ],
  },
];
