export const ROUTES = {
  ROOT: '/',
  HOME: '/home',
  FT_OAUTH: '/ftoauth',
  FT_OAUTH_REDIRECT: '/auth/ft/redirect',
  PROFILE_ROOT: '/profile',
  PROFILE_USERNAME: '/profile/:username/:tab',
  PROFILE_USERNAME_ROOT: '/profile/:username',
  PROJECT_ROOT: '/project',
  PROJECT_DETAIL: '/project/:projectName',
  LEADERBOARD: '/leaderboard/:tab',
  LEADERBOARD_ROOT: '/leaderboard',
  EVALLOG: '/evallog',
  SETTING: '/setting',
} as const;
