export const ROUTES = {
  ROOT: '/',
  HOME: '/home',
  FT_OAUTH: '/ftoauth',
  FT_OAUTH_REDIRECT: '/auth/ft/redirect',
  PROFILE: '/profile/:login',
  PROFILE_GENERAL_TAB: '/profile/:login/general',
  PROFILE_EVAL_TAB: '/profile/:login/eval',
  PROFILE_VERSUS_TAB: '/profile/:login/versus',
  PROFILE_OF: (login: string) => `/profile/${login}`,
  PROFILE_GENERAL_TAB_OF: (login: string) => `/profile/${login}/general`,
  PROFILE_EVAL_TAB_OF: (login: string) => `/profile/${login}/eval`,
  PROFILE_VERSUS_TAB_OF: (login: string) => `/profile/${login}/versus`,
  PROJECT_DETAIL: '/project/:projectName',
  PROJECT_DETAIL_OF: (projectName: string) => `/project/${projectName}`,
  LEADERBOARD: '/leaderboard',
  LEADERBOARD_LEVEL: '/leaderboard/level',
  LEADERBOARD_EXP_INCREMENT: '/leaderboard/exp_increment',
  LEADERBOARD_COALITION_SCORE: '/leaderboard/coalition_score',
  LEADERBOARD_EVAL_COUNT: '/leaderboard/eval_count',
  EVALLOG: '/evallog',
  SETTING: '/setting',
} as const;
