export const POKEMON = [
  ['starting', 'Togepi', 'abra', 'Espeon', 'Lugia', 'Mew', 'Mewtwo'],
  ['Geodude', 'Eevee', 'Marill', 'Raichu', 'Jolteon', 'Ampharos', 'Zapdos'],
  ['Onix', 'Dratini', 'Lapras', 'Haunter', 'Gengar', 'Mimikyu', 'Darkrai'],
  [
    'Steelix',
    'Lucario',
    'Happiny',
    'Lapras',
    'Dragonair',
    'Gyarados',
    'Kyogre',
  ],
  [
    'Golem',
    'Snorlax',
    'Arcanine',
    'Leafeon',
    'Togekiss',
    'Greninja',
    'Articuno',
  ],
  [
    'Tyranitar',
    'Lucario',
    'Charizard',
    'Sylveon',
    'Dragonite',
    'Salamence',
    'Solgaleo',
  ],
  [
    'Regigigas',
    'Zacian',
    'Moltres',
    'Shaymin',
    'Jirachi',
    'Rayquaza',
    'Arceus',
  ],
];
