name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.READ_PRIVATE_SUBMODULE_TOKEN }}

      - name: Build using Docker Compose
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: docker-compose.prod.yml

      - name: Install AWS
        run: |
          sudo apt-get update
          sudo apt-get install awscli
      - name: Copy built files to ./dist
        run: |
          mkdir -p ./dist
          cp -r ./app/dist/* ./dist/
      - name: Upload to S3
        uses: reggionick/s3-deploy@v3
        with:
          folder: ./dist
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{secrets.DEFAULT_BUCKET_REGION}}
