name: Upload build result to s3 bucket (production ver.)

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DEFAULT_BUCKET_REGION: ${{ secrets.DEFAULT_BUCKET_REGION }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
      WORKING_DIRECTORY: ./app

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          ref: main
          submodules: true
          token: ${{ secrets.READ_PRIVATE_SUBMODULE_TOKEN }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Pnpm setup
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: pnpm i
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Build
        run: pnpm run build
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Install AWS
        run: |
          sudo apt-get update
          sudo apt-get install awscli

      - name: Upload to S3
        run: |
          aws s3 sync ./app/dist s3://$S3_BUCKET --region $DEFAULT_BUCKET_REGION
